"use client";

import { useState } from 'react';
import { Card } from './Card';
import { backendPost } from '../lib/api';

export function EpisodeCreator() {
  const [contestantId, setContestantId] = useState('');
  const [title, setTitle] = useState('');
  const [media, setMedia] = useState('');
  const [status, setStatus] = useState<string>();

  const submit = async () => {
    try {
      setStatus('Submitting episode...');
      await backendPost('/api/register/episode', {
        contestantId,
        title,
        media,
        description: 'Generated by producer UI',
        royaltyBps: 300,
      });
      setStatus('Episode submitted to backend for Story registration.');
    } catch (err) {
      setStatus('Failed — check backend URL/env.');
    }
  };

  return (
    <Card title="Episode Creation" subtitle="Producers & fans can mint episodes" cta={<button onClick={submit}>Create</button>}>
      <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
        <input
          placeholder="Contestant ID"
          value={contestantId}
          onChange={(e) => setContestantId(e.target.value)}
          style={inputStyle}
        />
        <input placeholder="Episode title" value={title} onChange={(e) => setTitle(e.target.value)} style={inputStyle} />
        <input placeholder="Media URL" value={media} onChange={(e) => setMedia(e.target.value)} style={inputStyle} />
      </div>
      {status && <p style={{ color: 'var(--muted)' }}>{status}</p>}
    </Card>
  );
}

const inputStyle: React.CSSProperties = {
  background: 'rgba(255,255,255,0.05)',
  border: '1px solid rgba(255,255,255,0.1)',
  borderRadius: 8,
  padding: '10px 12px',
  color: 'var(--text)',
  minWidth: 160,
};

